export const countries = [
'Afghanistan',
'Albania',	
'Algeria',	
'Andorra',	
'Angola',
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Australia',
'Austria',
'Azerbaijan',
'Bahamas',
'Bahrain',
'Bangladesh',
'Barbados',
'Belarus',
'Belgium',
'Belize',
'Benin',
'Bhutan',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Brazil',
'Brunei',
'Bulgaria',
'Burkina Faso',
'Burundi',
"Côte d'Ivoire",
'Cabo Verde',
'Cambodia',
'Cameroon',
'Canada',
'Central African Republic',
'Chad',
'Chile',
'China',
'Colombia',
'Comoros',
'Congo',
'Costa Rica',
'Croatia',
'Cuba',
'Cyprus',
'Czech Republic',
'Democratic Republic of the Congo',
'Denmark',
'Djibouti',
'Dominica',
'Dominican Republic',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Eswatini',
'Ethiopia',
'Fiji',
'Finland',
'France',
'Gabon',
'Gambia',
'Georgia',
'Germany',
'Ghana',
'Greece',
'Grenada',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Holy See',
'Honduras',
'Hungary',
'Icelana',
'India',
'Indonesia',
'Iran',
'Iraq',
'Ireland',
'Israel',
'Italy',
'Jamaica',
'Japan',
'Jordan',
'Kazakhstan',
'Kenya',
'Kiribati',
'Kuwait',
'Kyrgyzstan',
'Laos',
'Latvia',
'Lebanon',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Marshall Islands',
'Mauritania',
'Mexico',
'Micronesia',
'Moldova',
'Monaco',
'Mongolia',
'Montenegro',
'Morocco',
'Mozambique',
'Myanmar',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'North Korea',
'North Macedonia',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Palestine State',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Poland',
'Portugal',
'Qatar',
'Romania',
'Russia',
'Rwanda',
'Saint Kitts and Nevis',
'Saint Lucia',
'Saint Vincent and the Grenadines',
'Samoa',
'San Marino',
'Sao Tome and Principe',
'Saudi Arabia',
'Senegal',
'Serbia',
'Seychelles',
'Sierra Leone',
'Singapore',
'Slovakia',
'Slovenia',
'Solomon Islands',
'Somalia',
'South Africa',
'South Korea',
'South Sudan',
'Spain',
'Sri Lanka',
'Sudan',
'Suriname',
'Sweden',
'Switzerland',
'Syria',
'Tajikistan',
'Tanzania',
'Thailand',
'Timor-Leste',
'Togo',
'Tonga',
'Trinidad and Tobago',
'Tunisia',
'Turkey',
'Turkmenistan',
'Tuvalu',
'Uganda',
'Ukraine',
'United Arab Emirates',
'United Kingdom',
'United States of America',
'Uruguay',
'Uzbekistan',
'Vanuatu',
'Venezuela',
'Vietnam',
'Yemen',
'Zambia',
'Zimbabwe']

export const states = [
  { state: 'Alabama', acronym: 'AL' },
  { state: 'Alaska', acronym: 'AK' },
  { state: 'Arizona', acronym: 'AZ' },
  { state: 'Arkansas', acronym: 'AR' },
  { state: 'California', acronym: 'CA' },
  { state: 'Colorado', acronym: 'CO' },
  { state: 'Connecticut', acronym: 'CT' },
  { state: 'Delaware', acronym: 'DE' },
  { state: 'District Of Columbia', acronym: 'DC' },
  { state: 'Florida', acronym: 'FL' },
  { state: 'Georgia', acronym: 'GA' },
  { state: 'Hawaii', acronym: 'HI' },
  { state: 'Idaho', acronym: 'ID' },
  { state: 'Illinois', acronym: 'IL' },
  { state: 'Indiana', acronym: 'IN' },
  { state: 'Iowa', acronym: 'IA' },
  { state: 'Kansas', acronym: 'KS' },
  { state: 'Kentucky', acronym: 'KY' },
  { state: 'Louisiana', acronym: 'LA' },
  { state: 'Maine', acronym: 'ME' },
  { state: 'Maryland', acronym: 'MD' },
  { state: 'Massachusetts', acronym: 'MA' },
  { state: 'Michigan', acronym: 'MI' },
  { state: 'Minnesota', acronym: 'MN' },
  { state: 'Mississippi', acronym: 'MS' },
  { state: 'Missouri', acronym: 'MO' },
  { state: 'Montana', acronym: 'MT' },
  { state: 'Nebraska', acronym: 'NE' },
  { state: 'Nevada', acronym: 'NV' },
  { state: 'New Hampshire', acronym: 'NH' },
  { state: 'New Jersey', acronym: 'NJ' },
  { state: 'New Mexico', acronym: 'NM' },
  { state: 'New York', acronym: 'NY' },
  { state: 'North Carolina', acronym: 'NC' },
  { state: 'North Dakota', acronym: 'ND' },
  { state: 'Ohio', acronym: 'OH' },
  { state: 'Oklahoma', acronym: 'OK' },
  { state: 'Oregon', acronym: 'OR' },
  { state: 'Pennsylvania', acronym: 'PA' },
  { state: 'Rhode Island', acronym: 'RI' },
  { state: 'South Carolina', acronym: 'SC' },
  { state: 'South Dakota', acronym: 'SD' },
  { state: 'Tennessee', acronym: 'TN' },
  { state: 'Texas', acronym: 'TX' },
  { state: 'Utah', acronym: 'UT' },
  { state: 'Vermont', acronym: 'VT' },
  { state: 'Virginia', acronym: 'VA' },
  { state: 'Washington', acronym: 'WA' },
  { state: 'West Virginia', acronym: 'WV' },
  { state: 'Wisconsin', acronym: 'WI' },
  { state: 'Wyoming', acronym: 'WY' },
]

export const cities = [	
'Kabul',
'Tirana' ,
'Algiers',
'Andorra la Vella',
'Luanda',
'Saint John\'s',
'Buenos Aires',
'Yerevan',
'Canberra',
'Vienna',
'Baku',
'Nassau',
'Manama',
'Dhaka',
'Bridgetown',
'Minsk',
'Brussels',
'Belmopan',
'Porto Novo',
'Thimphu',
'Sucre' ,
'Sarajevo',
'Gaborone',
'Brasilia',
'Bandar Seri Begawan',
'Sofia',
'Ouagadougou',
'Gitega',
'Phnom Penh',
'Yaounde',
'Ottawa',
'Praia',
'Bangui',
'N\'Djamena',
'Santiago',
'Beijing',
'Bogota',
'Moroni',
'Kinshasa',
'Brazzaville',
'San Jose',
'Yamoussoukro',
'Zagreb',
'Havana',
'Nicosia',
'Prague',
'Copenhagen',
'Djibouti',
'Roseau',
'Santo Domingo',
'Dili',
'Quito',
'Cairo',
'San Salvador',
'Malabo',
'Asmara',
'Tallinn',
'Mbabana',
'Addis Ababa',
'Palikir',
'Suva',
'Helsinki',
'Paris',
'Libreville',
'Banjul',
'Tbilisi',
'Berlin',
'Accra',
'Athens',
'Saint George\'s',
'Guatemala City',
'Conakry',
'Bissau',
'Georgetown',
'Port au Prince',
'Tegucigalpa',
'Budapest',
'Reykjavik',
'New Delhi',
'Jakarta',
'Tehran',
'Baghdad',
'Dublin',
'Rome',
'Kingston',
'Tokyo',
'Amman',
'Nur Sultan',
'Nairobi',
'Tarawa Atoll',
'Pristina',
'Kuwait City',
'Bishkek',
'Vientiane',
'Riga',
'Beirut',
'Maseru',
'Monrovia',
'Tripoli',
'Vaduz',
'Vilnius',
'Luxembourg',
'Antananarivo',
'Lilongwe',
'Kuala Lumpur',
'Male',
'Bamako',
'Valletta',
'Majuro',
'Nouakchott',
'Port Louis',
'Mexico City',
'Chisinau',
'Monaco',
'Ulaanbaatar',
'Podgorica',
'Rabat',
'Maputo',
'Nay Pyi Taw',
'Windhoek',
'Nauru'	,
'Kathmandu',
'Amsterdam',
'Wellington',
'Managua',
'Niamey',
'Abuja',
'Pyongyang',
'Skopje',
'Belfast',
'Oslo',
'Muscat',
'Islamabad',
'Melekeok',
'Jerusalem' ,
'Panama City',
'Port Moresby',
'Asuncion',
'Lima',
'Manila',
'Warsaw',
'Lisbon',
'Doha',
'Bucharest',
'Moscow',
'Kigali',
'Basseterre',
'Castries',
'Kingstown',
'Apia',
'San Marino',
'Sao Tome',
'Riyadh',
'Edinburgh',
'Dakar',
'Belgrade',
'Victoria',
'Freetown',
'Singapore',
'Bratislava',
'Ljubljana',
'Honiara',
'Mogadishu',
'Pretoria, Bloemfontein, Cape Town',
'Seoul',
'Juba',
'Madrid',
'Sri Jayawardenapura Kotte',
'Khartoum',
'Paramaribo',
'Stockholm',
'Bern',
'Damascus',
'Taipei',
'Dushanbe',
'Dodoma',
'Bangkok',
'Lome',
'Nuku\'alofa',
'Port of Spain',
'Tunis',
'Ankara',
'Ashgabat',
'Funafuti',
'Kampala',
'Kiev',
'Abu Dhabi',
'London',
'Washington D.C.',
'Montevideo',
'Tashkent',
'Port Vila',
'Vatican City',
'Caracas',
'Hanoi',
'Cardiff',
'Sana\'a',
'Lusaka',
'Harare'
]